on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        toolchain: [ "gcc", "clang"]
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.ccache
          key: ${{ runner.os }}-${{ matrix.toolchain }}-cacheID
      - uses: actions/checkout@v2
        with:
           fetch-depth: 200
           submodules: true
      - name: install core packages
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends apt-utils dialog git iproute2 procps lsb-release
      - name: add testing toolchain
        run: |
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
      - name: install tool chain
        run: |
          sudo apt-get -y install libstdc++6 clang-format-5.0 ccache
          if test "${{ matrix.toolchain }}" = "gcc" ; then
            sudo apt-get -y install cpp-6 gcc-6 g++-6 
          else
            sudo apt-get -y install clang-5.0 llvm-5.0
          fi
      - name: install dependencies
        run: sudo apt-get -y install postgresql git build-essential pkg-config autoconf automake libtool bison flex libpq-dev parallel
      - name: Build
        run: |
          if test "${{ matrix.toolchain }}" = "gcc" ; then
            export CC='gcc'
            export CXX='g++'
          else
            export CC='clang'
            export CXX='clang++'
          fi
          echo Build with $CC and $CXX
          ./travis-build.sh --use-temp-db
